Apple clone page project
ricardomonte/Building_Backgrounds_and_Gradients_Apple pull request #1
Opened 2020-08-24 21:59 UTC by ricardomonte

In this project:

    We structure the HTML using:

> Semantic

> Normalizer

> CSS stylesheet

> Linters

    We also create the style using:

> Backgrounds and Gradients

> CSS Flexbox

2020-08-24 22:39 UTC, kevcap requested changes
# [STATUS] CHANGES REQUIRED♻️

  ### Hi team, you guys did a very good job so far!
  #### I can see that you guys are working hard at this project, and you're almost done, there are just some required changes* that you guys have to implement in order to proceed:

  _Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, in order to get more knowledge and have a better project to add at your portfolio.
  
## [REQUIRED CHANGES]
#### Clone requirements 👥 (Those requirements to make your page really look like a clone)⤵
- [x] Please centralize the navbar (check the image with drawings below);
- [x] Kindly remove that gap at the left part (check the image with drawings below);
#### Good practices Requirements (Those requirements to make you code like a pro 👽)⤵
- [x] Files not related to the project should not be committed and added to .gitignore (e.g. .DS_Store, package-lock.json) ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png)from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Looks like you guys didn't update your README.md, I still can see text related to the NYT project ([screenshot ](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png)from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [x] Guys, next time take care of the frequency of the commits! Try to make sure that the commits stay as close as possible of 50/50.
- [x] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/91102782-3afa5080-e640-11ea-9971-eb05f9d9fb95.png)


## [OPTIONAL CHANGES]
#### Clone requirements 👥 (Those requirements to make your page really look like a clone)⤵
- [x] Add a favicon to make it more similar to the original page;
- [x] Change the title of the page to match with the original one (just Apple);
- [x] Improve the footer to make it more similar to the original one;
#### Good practices Requirements (Those requirements to make you code like a pro 👽)⤵
- [x] Replace Author1 and Author2 with your names;
<hr>
## Image (RED = REQUIRED; GREEN = OPTIONAL)

![image](https://user-images.githubusercontent.com/56762529/91102632-ed7de380-e63f-11ea-878d-afd9b138faf5.png)

## Summary
✨ Your CSS looks really organized and professional! 👨‍💻
✨ The project looks really nice 💯
✨ Good job with that project, it looks really good for a first review 💥
Just have to implement that minor changes listed above, and I know that It will be easy for you both! 🔧
## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀

  👨🏻‍💻 **TSE: Kevin Alves**

    

  📫 Have any question? Better call Kevin:

  <a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

    
  <sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-08-24 22:39 UTC, kevincappuccino commented on README.md
> +The third project for microverse, replicate this article from the New York Times: https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.h
Update this, please 😎.

2020-08-25 01:04 UTC, kitpao requested changes
# 👋 Hello @ricardomonte and @Nexch 

You did a nice job implementing most of the mandatory and optional suggestions given by the previous TSE 👏 The favicon and customized name add an extra professional touch to your project
You are only missing few changes, please check them below 🔽 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

You have the following issue in your layout and it seems it can be fixed if you follow a tip I'll give you in the inline comments ⬇️ 
- [x] The gap at the left is still showing, please ensure that the "products" section takes the full width as in the original page
![image](https://user-images.githubusercontent.com/53256139/91109226-f8d10f00-e63f-11ea-9cf9-a36a47e7d69c.png)

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-25 01:04 UTC, kitpao commented on css/style.css
> +}
- [ ] **OPTIONAL TIP FOR ALIGNING ITEMS** It seems you had to adjust everything with margins and your background had to be positioned manually also with `background-position: 0 -700px;`. That is why everything moves in different screen sizes.

It is not a requirement that it displays right in all screen sizes for this project, but believe me, it will make your life easier when doing layouts! 

An easy way to avoid these complications would be to add a div exclusively for the background image inside your main, with the size it should have since the beginning with the fewer elements it has inside (instead of using a main that has multiple things you should align). That way, the rest of the elements, should accommodate themselves automatically without clashing with each other.

Don't be afraid of using more divs, and let them accommodate without you having to specify measurements for the alignment.
![image](https://user-images.githubusercontent.com/53256139/91110047-55cdc480-e642-11ea-9437-18a0dc43a0de.png)

2020-08-25 01:04 UTC, kitpao commented on README.md
> +**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the currect project doesn't require testing.**
- [x] Please delete this because they are instructions for you, the authors, so you know how to use the template.

2020-08-25 01:04 UTC, kitpao commented on css/style.css
> +  display: block;
- [x] You did well making your code dry, but you are still missing some repeated rules, such as `display: block;` or `justify-content: space-between;`. Please put it in a class and call it from your HTML where you need them

2020-08-25 04:14 UTC, kitpao requested changes
# 👋 Hello again @ricardomonte and @Nexch 

You are almost there, you are missing only one thing:

- [x] Fixing the space to the sides. ![image](https://user-images.githubusercontent.com/53256139/91120946-65f29d80-e65c-11ea-8f15-b8678ec149c0.png)
  **Hint:** You put a 100% width to your `<ul>`, but the `<li>` inside have a fixed width based on the width you specified inside the `<a>` ( `width: 350px;`) That is why they are not taking the whole space. 
  Suggested steps:
  - Give a specific width to your li's in % units to divide it into 4 equal parts.
  - Delete the fixed with of your a's
  - Use the background-size property in your a's so that the images cover the whole space
  The result will look like this:
  ![image](https://user-images.githubusercontent.com/53256139/91122249-70fafd00-e65f-11ea-8621-733a90f1f210.png)


### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-08-25 16:17 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

## Hello @ricardomonte and @Nexch :wave: 

## Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

## You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-08-25 16:22 UTC, merged